### ISSUE TITLE
auro-dialog: a11y - focus not returned to previously active element

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-interruption#10]
## Describe the bug
When I close the modal using the keyboard, my focus is lost. Ideally, it should be returned to the previously-active element (e.g. the button that opened the modal). Per the WAI-ARIA Authoring Practices:

> When a dialog closes, focus returns to the element that invoked the dialog unless either: 
> - The invoking element no longer exists. Then, focus is set on another element that provides logical work flow.
> - The work flow design includes the following conditions that can occasionally make focusing a different element a more logical choice: 
>   1. It is very unlikely users need to immediately re-invoke the dialog.
>   2. The task completed in the dialog is directly related to a subsequent step in the work flow.
> 
> For example, a grid has an associated toolbar with a button for adding rows. the Add Rows button opens a dialog that prompts for the number of rows. After the dialog closes, focus is placed in the first cell of the first new row.

## To Reproduce
1. Open the dialog
2. Tab to the close button and trigger it
3. Keyboard focus is lost. At time of writing it remains on the close button (because of AlaskaAirlines/auro-dialog#6), but that is no longer visible on the page.

## Expected behavior
My focus is returned to the element that triggered the dialog.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox

## Additional context
Without implementing this, keyboard users will be confused as to where their focus went. They may think that they have to start tabbing from the start of the page.

**Comment by blackfalcon** [comment]
tested with PR ✅
