### ISSUE TITLE
UPDATE auro-interruption: Theming Support

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-interruption#107]
### Is your feature request related to a problem? Please describe.

This is regarding theming updates that need to happen to nearly all `auro` components

### Describe the solution you'd like

1. Update to latest WC Generator Template Standard (e.g. dependences, Node)
2. All tokens with the prefix `--auro` need to be renamed to `--ds` so they work with the new WCSS v5 update.
3. The WCSS package needs to be updated to ^5.0.0 and the import paths in the component *.scss files need to be updated as well
### Describe alternatives you've considered

None

### Additional context

Reference this `auro-button` pr https://github.com/AlaskaAirlines/auro-button/pull/231
And this `auro-hyperlink` pr https://github.com/AlaskaAirlines/auro-hyperlink/pull/185

### Exit criteria

All tokens referencing `--auro` have been updated.

**Comment by blackfalcon** [comment]
I recommend holding off on this and instead move to update the whole repo and possibly rebuild like we did Accordion and separate out DIALOG and DRAWER into independent repos.

**Comment by fajar-apri-alaska** [comment]
> I recommend holding off on this and instead move to update the whole repo and possibly rebuild like we did Accordion and separate out DIALOG and DRAWER into independent repos.

sure, I can work on it if this actually happens and when the tickets are ready.

**Comment by braven112** [comment]
> I recommend holding off on this and instead move to update the whole repo and possibly rebuild like we did Accordion and separate out DIALOG and DRAWER into independent repos.

If you can help break this work down into 2 parts.  We briefly talked about it in standup but its not clear to me what part is actually blocking the theming work and what part we are recommending we do "since we are already in there"

1. Get the repo ready to update the tokens.  What parts of the repo need to be updated outside of the token names?  Node updates?  Anything else?
2. Separating out Dialog and Drawer - Before we go to far down this road we'll need to weight this against all the other good ideas we have as well as consider any new ideas in the design space.  We can start to get a doc going to capture some of these ideas.

**Comment by blackfalcon** [comment]
If you want to just do the WCSS and token updates, that fine. My point is that this repo is way behind as far as NOde support is concerned and we need to get that addressed as well.

**Comment by jordanjones243** [comment]
This issue is no longer needed, as we have split auro-interruption into auro-dialog and auro-drawer standalone components:
- https://github.com/AlaskaAirlines/auro-dialog/pull/4
- https://github.com/AlaskaAirlines/auro-drawer/pull/5
