### ISSUE TITLE
auro-dialog: back navigation dismisses non-blocking modal

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-interruption#13]
## Is your feature request related to a problem? Please describe.
as a guest, if I am presented with a non-blocking dialog, I want to be able to dismiss this dialog by using browser navigation.

## Describe the solution you'd like
TBD

## Describe alternatives you've considered
TBD

## Additional context
Will fill more out later

**Comment by blackfalcon** [comment]
@gusnaughton I am throwing this back at you. This feels like an unfinished thought. Can you provide more context?

**Comment by blackfalcon** [comment]
I am closing this issue as there is little content for resolution.
