### ISSUE TITLE
auro-interruption: a11y report - some guests not understanding how to navigate blocking modals

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-interruption#41]
## Describe the bug
during the Flight Search a11y discovery, the following item came out:
![image](https://user-images.githubusercontent.com/7005799/126213277-a92d6f80-8510-4b21-9684-a7acc97ba85e.png)

Is there a way we can make blocking modals like this one more easy or intuitive for screen reader users to navigate?
https://components.alaskaair.com/catelog/demo/fs-saver-to-main-upsell

**Comment by blackfalcon** [comment]
When testing the dialog box option on the Auro site, per the use of [role="dialog"](https://a11ysupport.io/tech/aria/dialog_role) VoiceOver states, "You are currently on a dialog." This was tested on Chome, Edge, and Safari using macOS VoiceOver. That being said, I do understand that there are tools out there that are not living up to the specification set by `role="dialog"`.

It also can be argued that if the user did not see a way out of an option, then none was given within the context of the content. E.g. a `no` or `cancel` option. 

As a last option, the content of the dialog is in a `slot`, and users of the dialog have full control over the HTML inserted. E.g. if a user wishes to add additional context regarding the use of a dialog that is hidden from visual users, that is their prerogative. But we don't feel that adding additional content for all dialogs is an appropriate solution to this issue.

**Comment by gusnaughton** [comment]
@erikalanghauser thoughts on the above?

**Comment by erikalanghauser** [comment]
@gusnaughton , @blackfalcon  - Could the issue be that it's called 'dialog'? Has any competitive analysis been done (i.e. is this the common term being used by screen readers)? Even internally, most of us call it a modal so I am wondering if it's the lexicon...

**Comment by blackfalcon** [comment]
@erikalanghauser I'd argue that `modal` is the incorrect reference. It's commonly misunderstood. The term `modal` references the state of a `dialog` interaction. Here are some supporting references 

- [Modal & Nonmodal Dialogs: When (& When Not) to Use Them](https://www.nngroup.com/articles/modal-nonmodal-dialog/)
- [`<dialog>`: The Dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)
- [ARIA: dialog role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role)

> Dialogs can be modal or non-modal. When a modal dialog appears on the screen, it's not possible to interact with any page content outside the dialog. In other words, the main application UI or page content is considered to be temporarily disabled as long as the modal dialog is showing. For non-modal dialogs it is still possible to interact with content outside of the dialog while the dialog is showing. Note that for non-modal dialogs there will have to be a global keyboard shortcut that allows focus to be moved between opened dialogs and the main page.

-- [reference](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role#required_javascript_features)

**Comment by erikalanghauser** [comment]
@blackfalcon It does seem like we would be talking about a modal-dialog in this case though, correct? If "dialog" is what screen reader users are used to hearing, then great. I was questioning if hearing "dialog" was useful & understandable to them (in the case of the participant referenced, apparently it was not).

**Comment by erikalanghauser** [comment]
I think we can remove this story for the time being as it requires further investigation. It's not clear if the guest issue was:
1 - the lexicon used for the 'dialog' label
2 - the blocking aspect of it - do some sighted users have the similar issues with the blocking modal? Unfortunately it is built to force interaction and not be easy to exit.
3 - an edge case. This is one participant and is not necessarily reflective of all screen reader users' behavior.
