### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-interruption#46]
The following items are to be included with the next MAJOR release of the Auro WC-Generator, all PRs are to be from the feature branch to `v2.0-rc` branch.

- [ ] #27
- [ ] #40
- [ ] #42 
- [ ] #48
- [ ] #54 
- [ ] https://github.com/AlaskaAirlines/auro-interruption/issues/52

**Comment by braven112** [comment]
closing this rc in favor of issues and milestones
