### ISSUE TITLE
Scroll bar appear by default when scrollable

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-interruption#48]
## Is your feature request related to a problem? Please describe.
If a dialog or drawer is scrollable, can we have the scroll bar appear by default rather than only when scrolling?
There is currently an issue guests are experiencing because they do not know they can scroll the 'Get more with Main' blocking modal. The scroll bar only appears once you attempt to scroll (both in chrome and safari) and guests are not discovering this on their own.

## Describe the solution you'd like
If a dialog or drawer is scrollable, have the scroll bar appear by default so it is clear to guests they need to scroll for the rest of the content.

## Describe alternatives you've considered
At least having scroll bar appear when hovering over the dialog/drawer?

## Additional context
![image](https://user-images.githubusercontent.com/34354487/134568704-29f2d860-ef5e-4029-8562-3749bc2276c5.png)

**Comment by geoffrich** [comment]
I'm not certain, but this may primarily be an issue on Macs. IIRC, the default Mac behavior is to hide scrollbars until scrolling starts. On Windows (tested Firefox and Chrome), the scrollbar appears without scrolling:

![image](https://user-images.githubusercontent.com/4992896/134572752-f6fe60f9-9197-4732-8e9b-9283500f9c01.png)

**Comment by blackfalcon** [comment]
This has been a macOS setting since 2011 https://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/

There has been a hack to reverse this OS default, but it's not very popular https://stackoverflow.com/questions/7855590/preventing-scroll-bars-from-being-hidden-for-macos-trackpad-users-in-webkit-blin

> ... guests are not discovering this on their own.

How many users are we talking about here? This UX is very consistent across many other websites. E.g. see the dialog experience with [this Delta result](https://www.delta.com/flight-search/search-results?cacheKeySuffix=39f01580-8de2-4f90-855c-740b73d0c775).

**Comment by erikalanghauser** [comment]
Glad to hear it is not an issue on Windows. I do think this is still a poor user experience for Mac users within the context of the auro-dialog specifically. 

@blackfalcon that link takes me to the Delta homepage. I have found some example of others putting a persistent scroll bar in their dialog experiences (it appears prior to hovering or any scrolling action):
![image](https://user-images.githubusercontent.com/34354487/135362305-bcbf4817-ad8a-4888-8ecc-d2e32b3e5a57.png)

![image](https://user-images.githubusercontent.com/34354487/135362403-24ef26a3-6428-48aa-b9ed-ef4aca76819d.png)

**Comment by blackfalcon** [comment]
@erikalanghauser are you using a mouse with your computer or a trackpad? 

Aside from that, this is behavior that is managed at the OS level, for both macOS and WIndows. I am not comfortable hijacking a UI feature at this level. 

Out of the sample of users, how many had issues with this interaction? Given that sample, an assumed numbers of users that may have that issue are? 

Is there an opportunity for compromise? A popular affordance is an arrow that appears prior to interaction and dismisses with scrolling.

**Comment by blackfalcon** [comment]
This issue has been marked as abandoned. Unless there is feedback to assist with updates, this issue will be closed in 30 days.
