### ISSUE TITLE
auro-dialog: rapidly closing and opening the modal does not show the modal

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-interruption#5]
## Describe the bug
If I close the modal and immediately open it again, the screen darkens but the modal is not displayed.

![dialog](https://user-images.githubusercontent.com/4992896/101094747-b89ff780-3571-11eb-81f8-ec3079fb8670.gif)

## To Reproduce
1. Open the dialog
2. Close the dialog and immediately open it again
3. The screen darkens but the content is not displayed

## Expected behavior
The content is always displayed when the modal is open.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: latest Firefox

## Additional context
I think it's related to these lines: https://github.com/AlaskaAirlines/auro-dialog/blob/d0eaee489248c929c5d8622e73337302c5d27816/src/auro-dialog.js#L113-L131

Why is a timeout needed here?

**Comment by blackfalcon** [comment]
Validated with PR ✅
