### ISSUE TITLE
auro-interruption: drawer margin impacts content slot when scrolled

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-interruption#55]
## Describe the bug
The margin set around the auro-drawer impacts the content slot when scrolled.

## To Reproduce
www.alaskaair.com/status/day/today/2 and click View Seat Map - scroll down in the seat map to hide the header.

## Expected behavior
The margin should only apply to the top of the modal and not the top of the window when scrolled.

https://user-images.githubusercontent.com/7005799/142068914-4ce14685-7ca3-424a-91fd-ce2a8b49778b.mov

**Comment by braven112** [comment]
@gusnaughton  Have you tried the unformatted version of the dialog?

https://auro.alaskaair.com/components/auro/interruption/drawer#unformatted-drawer

Seems like that would give you the control of the padding you are looking for?  Let me know if that would solve it for you.

**Comment by blackfalcon** [comment]
At second glance... @braven112 and I discussed this and wouldn't it make more sense to use the `unformatted` attribute versus changing the default padding?

**Comment by blackfalcon** [comment]
I am re-opening this. In retrospect, I feel that this may not have been the correct solution to this issue. 

In your project, can you use the `unformatted` attribute and see if this addresses the layout issues you were having? It should remove all inset padding within the `content` slot. 

With that, I am thinking that we should revert the update with the linked PR.

**Comment by blackfalcon** [comment]
Discussed this with @gusnaughton and the merge stands as is. There is an opportunity for future updates regarding more access to the UI API, but for now we can go with this.
