### ISSUE TITLE
auro-interruption: Sticky Footer

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-interruption#57]
## Is your feature request related to a problem? Please describe.

The footer slot on the ~~modal~~ dialog box is not sticky (always in view) in circumstances where the content overflows the slot. For some use cases such as our saver to main upsell, we'd like to ensure that the buttons are always visible on the bottom of the modal in the footer slot.

## Describe the solution you'd like
Adjust the footer slot to always be visible on the bottom, rather than having it be scrollable.

**Comment by gusnaughton** [comment]
![image](https://user-images.githubusercontent.com/7005799/142086925-080ccfbe-df15-4481-9d77-7ef84ce3a1c1.png)

**Comment by blackfalcon** [comment]
We have no design specification for when content scrolls behind the action buttons. The original specification for this element specifically called for the content to scroll. 

<img width="547" alt="Screen Shot 2021-11-17 at 11 52 30 PM" src="https://user-images.githubusercontent.com/181089/142374357-019e4b29-4718-47a6-a263-6a6a09a98761.png">

I am all for updating the element, but I need to know what this will look like when the content scrolls.

**Comment by gusnaughton** [comment]
@erikalanghauser  are there design specs for sticky footer to fix the get more with main modal?

**Comment by erikalanghauser** [comment]
@gusnaughton no, there are no design specs for this currently. The story in our current sprint is to clean up the whitespace for MVP, not create a new sticky footer pattern.

**Comment by blackfalcon** [comment]
@erikalanghauser and @gusnaughton what is the call here? Am I to assume that this is not a feature we are going after and this and the linked PR should be closed?

**Comment by erikalanghauser** [comment]
@blackfalcon this feature is not an immediate need as we are trying to get MVP out, but is something that will make sense to have down the road. I don't have the capacity to update the auro-dialog specs currently. @leeejune if this something you would be interested in taking on, let me know and we can sync.
If not, how do we make sure this work isn't lost?

**Comment by braven112** [comment]
We'll leave this issue open and keep it in our backlog.  Sounds like we can close the PR though.  Thanks for the additional details!  If you are looking to get it developed definitely reach out to myself or @leeejune.  We'll need to make sure any features on the doc site match our design specs in Figma.

**Comment by leeejune** [comment]
@erikalanghauser This is definitely something I'd like to take on. We have auro-dialog in our backlog, so I will make sure to be aware of this when creating the specs!

**Comment by blackfalcon** [comment]
> @erikalanghauser This is definitely something I'd like to take on. We have auro-dialog in our backlog, so I will make sure to be aware of this when creating the specs!

@leeejune was there any movement on this since November of 21? If not, I am thinking we need to close this issue.

**Comment by leeejune** [comment]
@blackfalcon Nope. Dialog wasn't something prioritized and never got to it.

**Comment by blackfalcon** [comment]
I am electing to close this issue as there is no current followup. @leeejune and @erikalanghauser at such time there is a design exploration onto this, I will look to you to create a new issue for the defined work.
