### ISSUE TITLE
auro-interruption: warning when installing on Node > 12

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-interruption#60]
## Describe the bug
When installing the package, you receive a warning in the console if you're running on a version of node > 12.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@alaskaairux/auro-interruption@1.3.3',
npm WARN EBADENGINE   required: { node: '<=12.22.6' },
npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '8.1.1' }
npm WARN EBADENGINE }
```

## To Reproduce
1. Run node 14 (or 16)
2. Install this package
3. See warning

## Expected behavior
No warning is logged.

**Comment by blackfalcon** [comment]
The issue was caused by a misunderstanding of the `engines` property in the package.json.

**Comment by blackfalcon** [comment]
The issue should be resolved with this commit https://github.com/AlaskaAirlines/auro-interruption/commit/eb840e13ddb04c85f46c09199697c8ba1c61f9c8
