### ISSUE TITLE
auro-interruption: [the close button's toggle event does not fire in React]

### ISSUE THREAD

**Issue by nateatalaska** [AlaskaAirlines/auro-interruption#69]
## Describe the bug
When using the auro-dialog in React[17/18], the event `toggle` does not fire. 

## To Reproduce
```js
<auro-dialog open={someStateForOpen} onToggle={() => console.log('do something'}> // does not fire
  <span slot="header">header</span>
  <span slot="content">{content}</span>
</auro-dialog>
```

## Expected behavior
The callback function in the toggle should fire.

## Desktop (please complete the following information):
 - macOS Big Sur [11.3.1]
 - Edge

## Smartphone (please complete the following information):
 - Version 98.0.1108.56 (Official build) (x86_64)

## Additional context
This current workaround works, but it's tedious:
- https://css-tricks.com/3-approaches-to-integrate-react-with-custom-elements/#aa-approach-2-use-a-wrapper

**Comment by blackfalcon** [comment]
The `toggle` is a custom event type, so I am pretty sure that `onToggle` won't work. 

Using the demo in the element repo, I added the following code. 

```js
const source = document.getElementById('defaultDialog');

const inputHandler = function(e) {
  console.log(e.type);
}

source.addEventListener('toggle', inputHandler);
```

This will alert the event has fired with the event type of `toggle` by either clicking the button in the UI or the X. 

![toggle event](https://user-images.githubusercontent.com/181089/160726480-48cb5fe9-4083-4347-beb5-80bde4e08af5.gif)

**Comment by blackfalcon** [comment]
In regard to the React wrapper, help me understand the statement. It is common practice when using a universal element such as a HTML custom element to wrap in a specific framework to have a common API. If creating a React wrapper around this element helps with this feature, that would be a great addition to this repo.

**Comment by nateatalaska** [comment]
> Unfortunately, due to the nature of React's synthetic event system, you won't be able to listen to the custom toggle event using `<auro-dialog onToggle>`. There's no way around this from the Auro side -- currently, React just won't let you listen to custom events like this. This could be possible when React 19 is released with improved custom element support. Until then, the workaround is as you linked in the [CSS-Tricks](https://css-tricks.com/3-approaches-to-integrate-react-with-custom-elements/#aa-approach-2-use-a-wrapper) article.
> 
> To make this less tedious in your application, I would recommend wrapping auro-dialog in your own `Dialog` component so that you only have to manually attach the event listeners in one place, and everything else can use the React interface. This would also let you centralize the boolean attribute conversion in one place (e.g. `open={open ? "" : undefined}`) For example:
> 
> ```js
> // Dialog.js
> import '@alaskaairux/auro-interruption/dist/auro-dialog';
> import React, { useRef, useEffect } from 'react';
> 
> function Dialog(props) {
>     const ref = useRef();
>     const { open, onToggle, children } = props;
> 
>     function invokeCallback(event) {
>         if (onToggle) {
>             onToggle(event);
>         }
>     }
> 
>     useEffect(() => {
>         const { current } = ref;
>         current.addEventListener('toggle', invokeCallback);
>         return () => {
>             current.removeEventListener('toggle', invokeCallback);
>         }
>     });
>     
> 
>     return <auro-dialog ref={ref} open={open ? "" : undefined}>
>         {children}
>     </auro-dialog>
> }
> 
> export default Dialog;
> ```
> 
> Then throughout your app, you can import this Dialog component, and interact with it in a way more idiomatic to React. This is the beauty of a component-based framework - it lets you make your own abstractions!
> 
> ```js
> // App.js
> import React, { useState } from 'react';
> import './App.scss';
> import Dialog from './Dialog';
> 
> function App() {
>   const [open, setOpen] = useState(false);
> 
>   const openDialog = () => {
>     setOpen(true);
>   }
> 
>   const closeDialog = () => {
>     setOpen(false);
>   }
> 
>   return (
>     <main>
>       <p>Open: {open ? 'true' : 'false'}</p>
> 
>       <auro-button onClick={openDialog}>Open dialog</auro-button>
> 
>       <Dialog open={open} onToggle={closeDialog}>
>         <span slot="header">Important information</span>
>         <p slot="content">Hello, I'm a dialog</p>
>       </Dialog>
>     </main>
>   );
> }
> 
> export default App;
> ```
> 
> If you think it would be valuable, the Auro team could include a similar React component wrapper in the package to make interacting with this element easier.

@geoffrich Thank you for the post! This is actually what I am doing (TypeScript version) in the booking site's React project and it's working well. Glad to know we had the same idea of a Dialog component. 

I think a React component wrapper will definitely make it easier for others who may be using this for the first time in their projects too.

**Comment by jordanchang** [comment]
We're using v1.3.5 in our React App and the toggle event is working for us without any workaround or additional event handling code. 🤷🏽‍♂️

![image](https://user-images.githubusercontent.com/3304352/169876406-3a4fc901-ec11-40b5-86a8-11a3f250eacd.png)
![image](https://user-images.githubusercontent.com/3304352/169876846-162788e5-41fb-4545-b0d5-9a477bcaf868.png)

**Comment by blackfalcon** [comment]
@jordanchang what version of React are you using?

**Comment by jordanchang** [comment]
We're using React v16.14.0.

**Comment by blackfalcon** [comment]
In the end, this issue is difficult to address from our perspective as there is little we can do and most of the work is around creating a React wrapper. 

A wrapper was proposed, but not accepted as it's not a solution that works with the team who filed the issue. This all leads to the point that the element itself relies on standards and React does not. Wrappers are highly customized per the team's development opinions. So for Auro to create wrappers would result in a lot of work with little benefit to users. 

That with the fact that as @jordanchang pointed out, with a subtle difference in dev environments, no wrapper is needed. 

I am canceling this issue as there is no clear work that can be delivered to resolve it.
