### ISSUE TITLE
auro-dialog: a11y - escape key does not close dialog

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-interruption#7]
## Describe the bug
Per [WAI-ARIA authoring practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal), the escape key should close the dialog.

## To Reproduce
1. Open the dialog
2. Hit the escape key
3. Nothing happens

## Expected behavior
The escape key closes the dialog.

## Additional context
I assume this should only happen in a non-blocking context, i.e. when the close button is shown.

**Comment by blackfalcon** [comment]
Tested with PR ✅
