### ISSUE TITLE
auro-interruption: Allow dialog height to be set

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-interruption#71]
## Is your feature request related to a problem? Please describe.
The doc site states that "The size attribute effects the width of the desktop dialog. **Its height is dictated by the content.** "
I don't believe this is an accurate statement. The height seems to be maxed at a percentage of the browser viewport height and the content only sets the height if the content is smaller than what percentage is budgeted for the dialog. Is that right?

This is a problem, especially in the sm size dialog and modals that require interaction from the guest. At typical tablet and dektop viewport sizes, only 3-4 lines of text are fitting before requiring scroll, a less than ideal user experience.

## Describe the solution you'd like
I would like the engineers to have flexibility to set the max height, a fixed height, or a dialog-height to viewport-height ratio so we can fit the necessary content into the modals and eliminate the need to scroll for a few more lines or to see their options.

## Describe alternatives you've considered

Using a larger size modal - but not ideal to have to leverage extra whitespace in the width of a modal just to get more height. Also is not guaranteed to give enough height the way it's currently built.

## Additional context

Tablet (1024x768px) - Why can't I leverage this extra height (in red) on the page for my dialog content?
![image](https://user-images.githubusercontent.com/34354487/169616344-301af894-bfaa-419f-abb4-dc9f21d203c7.png)

Desktop (1440x900px) - Why can't I leverage this extra height (in red) on the page for my dialog content?
![image](https://user-images.githubusercontent.com/34354487/169616513-9e8818e4-5a76-4aea-a06a-1dc38b3d0aea.png)

Live example: Currency converter in sm dialog on Desktop (1440x900) - It looks broken/confusing and the guest has to scroll to submit to convert. The md size would take up too much unnecessary width on the page.
![image](https://user-images.githubusercontent.com/34354487/169616953-43aeaba8-d6ee-44b8-be4c-66c7330f33c4.png)
![image](https://user-images.githubusercontent.com/34354487/169617088-ee615905-43b7-40a2-bdfa-7907dcf70b63.png)

**Comment by blackfalcon** [comment]
The dialog window is pre-designed to fit three specific configurations. There is another related one-off customization requested. 

It is preferred that Auro open the styling API with CSS parts to allow engineers their additional micro customizations.

**Comment by blackfalcon** [comment]
Turns out looking at the code, there was an update that caused this regression. The scope of the work is to FIX the CSS cascade so that the UI is equal to the description.
