### ISSUE TITLE
auro-interruption: Close (X) button in wrong position unformatted dialog/drawer

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-interruption#72]
## Describe the bug
When using the auro-dialog or auro-drawer with unformatted=true and when screen width is >= 1024px, the Close (X) button is positioned where it will mostly likely overlap with content.

## To Reproduce
1. Create a <auro-dialog unformatted={true} />
2. Open dialog with screen width set to 1024px
3. Close (X) Button appears with a margin larger than typically expected by most designs.

## Expected behavior
The Close (X) button should be positioned in the upper-right corner with the same margins across all device screens.

## Screenshots
1024px width
![image](https://user-images.githubusercontent.com/3304352/169878117-3f20096d-b16d-446c-a23d-54a64a4ec95d.png)

1023px width
![image](https://user-images.githubusercontent.com/3304352/169878159-3c341666-a6e2-451a-8525-d25010e36228.png)

## Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Chrome
 - Version latest

## Smartphone (please complete the following information):
untested

## Additional context
none

**Comment by blackfalcon** [comment]
@jordanchang I can't say that this is a bug. This is consistent with the feature as it was designed. The best solution here is to update the CSS of the X element to listen to CSS Parts that will allow you to have control over the position of the X from the scope of your app.

**Comment by jordanchang** [comment]
> @jordanchang I can't say that this is a bug. This is consistent with the feature as it was designed. The best solution here is to update the CSS of the X element to listen to CSS Parts that will allow you to have control over the position of the X from the scope of your app.

Do you have an example of how to do this? The (X) button is in the shadow DOM.  I want to override the top and right positions with something like this, but

`:host([unformatted]) button.dialog-header--action {
  top: var(--auro-size-xl);
  right: var(--auro-size-xl);
}`
