### ISSUE TITLE
auro-interruption: SM and MD are same size

### ISSUE THREAD

**Issue by isaiahscheel** [AlaskaAirlines/auro-interruption#79]
## Describe the bug
- When changing the auro-drawer to either SM or MD, I am seeing that they are the same width. 
## To Reproduce
- Go to https://auro.alaskaair.com/components/auro/interruption/drawer
- Open the default drawer
- open the md drawer
- open the sm drawer
- I am seeing the sm and md drawer the same width 

## Expected behavior
- My expected behavior would be that MD would be somewhere in the middle of the default drawer width and the SM (and currently MD) drawer width
## Screenshots
From the auro site: 

![image](https://user-images.githubusercontent.com/40191651/183513115-074feaae-a574-441e-b2aa-f8ce3d775c48.png)

![image](https://user-images.githubusercontent.com/40191651/183513166-db46a74a-9454-4200-af6e-2accfb441f49.png)

## Desktop (please complete the following information):
 - OS: macOS
 - Browser chrome
 - Version  103.0.5060.134

## Smartphone (please complete the following information):
- n/a

## Additional context
- I do not have specs on what the exact width should be, however, it did seem odd that the width was not changing between the two sizes

**Comment by braven112** [comment]
Thanks for submitting this!  We are currently looking into our grid specifications and one of the outcomes of that should also be to standardize what sm, or md mean across all of our components.  Once that is complete it should make this one easier to address.

**Comment by isaiahscheel** [comment]
Thank you Brandon! Is there any work around now for a custom size or anything? You may be able to see in my PR above that we are needing to iframe in a section to look up discount codes in a drawer so we do not have a ton of control on the size and the default is way too large while the small/medium size is too small and cutting off words. Thanks for any help

**Comment by blackfalcon** [comment]
The definitions for this element were made at a time when user customizations were not really popular. I would argue that things have changed in the years since those decisions were made. 

Outside of the grid work that @braven112 is talking about, I would also suggest that we create a new work item for creating customizable access to the drawer/dialog via CSS shadow parts (https://auro.alaskaair.com/components/auro/interruption/api)

**Comment by braven112** [comment]
I talked with @erikalanghauser and @bridgetglewis to get more details.  The discount code information that is being pulled in get's cut off at the size they are using now.  They tried the default size but it was way too big.  We'll refine this more on Thursday but in general I like the idea of having some good s,m,l defaults along with a custom option like you mentioned @blackfalcon that way we aren't blocking teams that need to make adjustments for specific use cases.

**Comment by braven112** [comment]
@isaiahscheel Now that we released a new version of auro-interruption with MD sizes can you confirm that this fixes the issue where the drawer isn't wide enough to house the discount code info on the new search page?  I think most or all of the drawers are trying to use the MD size on the new search page.
