### ISSUE TITLE
auro-dialog: a11y - focus is not trapped within the dialog

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-interruption#8]
## Describe the bug
Per [WAI-ARIA authoring practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal), focus should be trapped within the dialog.

> When a dialog opens, focus moves to an element inside the dialog. See notes below regarding initial focus placement.
>
> Tab:
> - Moves focus to the next tabbable element inside the dialog.
> - If focus is on the last tabbable element inside the dialog, moves focus to the first tabbable element inside the dialog.
>
> Shift + Tab:
>  - Moves focus to the previous tabbable element inside the dialog.
>  - If focus is on the first tabbable element inside the dialog, moves focus to the last tabbable element inside the dialog.

> When a dialog opens, focus placement depends on the nature and size of the content.
> 
> -  In all circumstances, focus moves to an element contained in the dialog.
> -  Unless a condition where doing otherwise is advisable, focus is initially set on the first focusable element.
> -  If content is large enough that focusing the first interactive element could cause the beginning of content to scroll out of view, it is advisable to add tabindex="-1" to a static element at the top of the dialog, such as the dialog title or first paragraph, and initially focus that element.
> -  If a dialog contains the final step in a process that is not easily reversible, such as deleting data or completing a financial transaction, it may be advisable to set focus on the least destructive action, especially if undoing the action is difficult or impossible. The Alert Dialog Pattern is often employed in such circumstances.
> -  If a dialog is limited to interactions that either provide additional information or continue processing, it may be advisable to set focus to the element that is likely to be most frequently used, such as an "OK" or "Continue" button.

## To Reproduce
1. Open the dialog with the keyboard. Notice that focus is not moved inside the dialog.
2. Tab through the dialog. Notice that you can escape the dialog.

## Expected behavior
When I open the dialog with the keyboard, my focus is moved inside the dialog. When I continue tabbing within the dialog, I am unable to escape the dialog.

On opening the dialog, focus should likely be moved to either the close button (if non-blocking) or the button that dismisses the dialog (if blocking).

## Additional context
This is important to give keyboard users the same experience as those navigating with a mouse. Mouse users are unable to trigger any elements outside the dialog, so keyboard users should be unable to as well. Currently, keyboard users can tab to any element on the page and activate it, even when the dialog is open.

**Comment by geoffrich** [comment]
#19 partially fixes this, but there still is an issue with other Auro elements receiving focus. This will need to be investigated further.

**Comment by blackfalcon** [comment]
I am removing the BUG label as the more I think about this, this is not a bug with the element, but more so a complete lack of support from browsers. 

Take this tweet for example: https://twitter.com/passle_/status/1352359796171800578

And this custom element: https://www.webcomponents.org/element/@a11y/focus-trap

What I see here is an opportunity to create another custom element that is only for the purpose of trapping the focus of a user in their experience. 

This auro-focus-trap element should be a stand-alone element?

**Comment by geoffrich** [comment]
I was able to resolve this issue by swapping out the polyfill we're using for `inert`. If we still need to consider a custom element for focus trapping, we should create a separate defect to track that work.
