### ISSUE TITLE
auro-dialog: a11y - screen readers can escape the active dialog

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-interruption#9]
## Describe the bug
When the dialog is open, screen readers can still navigate to content outside of the dialog. Per the [WAI-ARIA authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal) (emphasis mine):

> A dialog is a window overlaid on either the primary window or another dialog window. Windows under a modal dialog are inert. That is, _users cannot interact with content outside an active dialog window._

## To Reproduce
1. Open the dialog while using a screen reader
2. Attempt to navigate out of the screen reader (e.g. to next button or form field)
3. Notice you are able to escape the modal

## Expected behavior
Screen reader users can only interact and navigate to content within the modal.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox w/ NVDA

## Additional context
This is a separate issue from AlaskaAirlines/auro-interruption#8. Trapping keyboard focus does not necessarily trap a screen reader's virtual cursor. Setting `aria-modal="true"` could fix the issue, though there is [an open WebKit issue](https://bugs.webkit.org/show_bug.cgi?id=174667) where setting aria-modal prevents VoiceOver from reading static text within the dialog (not good). 

Another solution is [setting aria-hidden on content outside the dialog](https://developer.paciellogroup.com/blog/2018/06/the-current-state-of-modal-dialog-accessibility/). However we solve this, we will need to thoroughly test with desktop and mobile screen readers to make sure it is behaving as expected.

**Comment by geoffrich** [comment]
#19 partially fixes this, but there still is an issue with other Auro elements receiving focus. This will need to be investigated further.

**Comment by blackfalcon** [comment]
Resolved: https://github.com/AlaskaAirlines/auro-interruption/pull/25
